name: Terraform CI/CD

on:
  pull_request:
    branches: ["main"]

  push:
    branches:
      - main # Triggers apply when changes are merged to main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
        working-directory: infra

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      # - uses: terraform-linters/setup-tflint@v3
      #   with:
      #     tflint_version: latest

      # - name: Show version
      #   run: tflint --version

      # - name: Init TFLint
      #   run: tflint --init
      #   working-directory: infra

      # - name: Run TFLint
      #   run: tflint -f compact
      #   working-directory: infra

      # - name: Checkov
      #   uses: bridgecrewio/checkov-action@master
      #   with:
      #     framework: terraform
      #     directory: infra

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: infra

  Apply:
    needs: CI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Ensures apply runs only on merges to main

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra
